// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GoogleJWT is an autogenerated mock type for the GoogleJWT type
type GoogleJWT struct {
	mock.Mock
}

// NewGoogleJWT creates a new instance of GoogleJWT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleJWT(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleJWT {
	mock := &GoogleJWT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
