linters:
  enable-all: false
  disable-all: false
  fast: false
  enable:
    - forbidigo
    - unused
    - dupl
  disable:
    - errcheck
    - wrapcheck
linters-settings:
  forbidigo:
    exclude-godoc-examples: true
    analyze-types: true
    forbid:
      - p: ^fmt\.Print.*$
        msg: forbid print statement
