// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppCrypto is an autogenerated mock type for the AppCrypto type
type AppCrypto struct {
	mock.Mock
}

// ComparePasswords provides a mock function with given fields: password, hashedPassword
func (_m *AppCrypto) ComparePasswords(password string, hashedPassword string) error {
	ret := _m.Called(password, hashedPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(password, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HashAndSalt provides a mock function with given fields: pwd
func (_m *AppCrypto) HashAndSalt(pwd []byte) (string, error) {
	ret := _m.Called(pwd)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (string, error)); ok {
		return rf(pwd)
	}
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(pwd)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(pwd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppCrypto creates a new instance of AppCrypto. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppCrypto(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppCrypto {
	mock := &AppCrypto{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
