// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GoogleJWT is an autogenerated mock type for the GoogleJWT type
type GoogleJWT struct {
	mock.Mock
}

type mockConstructorTestingTNewGoogleJWT interface {
	mock.TestingT
	Cleanup(func())
}

// NewGoogleJWT creates a new instance of GoogleJWT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGoogleJWT(t mockConstructorTestingTNewGoogleJWT) *GoogleJWT {
	mock := &GoogleJWT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
