// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	dto "activity-reporter/shared/dto"

	mock "github.com/stretchr/testify/mock"
)

// JwtTokenizer is an autogenerated mock type for the JwtTokenizer type
type JwtTokenizer struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: user
func (_m *JwtTokenizer) GenerateToken(user dto.UserTokenDTO) (string, error) {
	ret := _m.Called(user)

	var r0 string
	if rf, ok := ret.Get(0).(func(dto.UserTokenDTO) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.UserTokenDTO) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJwtTokenizer interface {
	mock.TestingT
	Cleanup(func())
}

// NewJwtTokenizer creates a new instance of JwtTokenizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJwtTokenizer(t mockConstructorTestingTNewJwtTokenizer) *JwtTokenizer {
	mock := &JwtTokenizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
